modLoader="javafml"
loaderVersion="[0,)"
license="MIT"
issueTrackerURL="https://github.com/ojaha065/PiShockForMC/issues"

[[mods]]
modId="pishockmc"
version="1.21-2.0.1.0"
displayName="PiShock for Minecraft"

#updateJSONURL="https://change.me.example.invalid/updates.json" # TODO
displayURL="https://github.com/ojaha065/PiShockForMC"
logoFile="logo.png" # TODO: An actual proper logo. This is just 5-minutes-in-photoshop placeholder...

credits="Special thanks to PiShock and its main developer Fedack/Lethos (https://twitter.com/Lethos_OTStorm) for making this mod possible :)"
authors="JHaiko"
description='''
PiShock Shock Collar Integration for Minecraft

This simple client-only mod allows players to connect their PiShock device to the game for some added stakes. Whenever the player takes damage, they will get a corresponding shock, the intensity of which can be configured and will scale up based on the amount of damage taken.

For detailed setup instructions and configuration, please refer to the GitHub page.

---

The authors of this mod are not responsible for any harm caused by misuse of the shock collar sold along with the PiShock device. We do not recommend putting any kind of electrical device near the heart or use if you have a heart condition. Shock collars are not meant for use on humans and can cause serious injury including cardiac events.
'''

# Display Test controls the display of the mod in the server connection screen
displayTest="IGNORE_ALL_VERSION" # This is a client-only mod

[[dependencies.pishockmc]]
    modId="forge"
    mandatory=true
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.pishockmc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21,1.22)"
    ordering="AFTER"
    side="BOTH"